pulp-platform/axi

CHANGELOG.md
src/axi_cut.sv
src/axi_id_remap.sv
src/axi_intf.sv
src/axi_join.sv
src/axi_lite_cut.sv
src/axi_lite_join.sv
src/axi_lite_multicut.sv
src/axi_lite_to_axi.sv
src/axi_lite_xbar.sv
src/axi_modify_address.sv
src/axi_multicut.sv
src/axi_to_axi_lite.sv
test/synth_bench.sv

Remove interface name aliasing to keep VCS happy

---

src/axi_multicut.sv

Restructure the AXI multicut to not need explicit case detection for 0, 1 or more cuts.

:art: Remove one level of generate from multicut

---

CHANGELOG.md
src/axi_pkg.sv
src/axi_test.sv
test/tb_axi_atop_filter.sv

- `axi_test`: Constrained randomizing AXI master (`rand_axi_master`) and slave (`rand_axi_slave`).
- `rand_axi_master` issues a configurable number of read and write transactions to configurable memory regions (address ranges with associated memory types) and with random properties within constraints (e.g., burst length, exclusive accesses, atomic operations).
- `rand_axi_slave` responds to transactions with random delays and data.
- `axi_pkg`: AXI memory types (`mem_type_t`) and functions `get_arcache` and `get_awcache` to calculate `AxCACHE` bits for a given memory type.
- `axi_test`: The `reset` tasks in `axi_driver` and `axi_lite_driver` are now functions.

axi_test: Add constrained randomizing master and slave

---

CHANGELOG.md
doc/axi_xbar.md
src/axi_pkg.sv

* Fix xbar_latency_e with explicit `CUT_ALL_PORTS`, issue is that vivado incorrectly extends 
`enum logic [9:0] LatencyMode = '1` to 10'b000000001. Workaround: explicit definition
* Add note in [doc/axi_xbar.md](https://github.com/WRoenninger/axi/blob/axi_pkg_vivado_fix/doc/axi_xbar.md) how `LatencyMode` should be configured when connecting two `axi_xbar` in duplex.

Add fix for vivado not correctly extending enum with '1

---

Bender.yml
src/axi_lite_xbar.sv

Prior to this patch, synthesis in DC failed for `axi_lite_xbar` with `NoMstPorts == 1` due to width mismatches between the `i_axi_aw_decode.idx_o` port and the `dec_aw` signal (and analogously for the AR) and on the `default_mst_port_i`.  The problem was introduced by declaring logic arrays with `[$clog2(Cfg.NoMstPorts)-1:0]`, which evaluated to `[-1:0]` for `Cfg.NoMstPorts == 1`.

Fix synthesis of `axi_lite_xbar`

---

Bender.yml
CHANGELOG.md
README.md
scripts/run_vsim.sh
src/axi_cdc.sv
test/synth_bench.sv
test/tb_axi_cdc.sv

This adds AXI CDCs which are based on the safer FIFO Gray design from our `common_cells` library.
Todo:

Add AXI CDCs

---

CHANGELOG.md
src/axi_demux.sv
src/axi_mux.sv

Change `axi_mux` and `axi_demux` interface wrapper name and parameters to be consistent to the other AXI modules with similar constructs.

Fix demux intf

---

CHANGELOG.md
src/axi_atop_filter.sv
src/axi_demux.sv
src/axi_id_prepend.sv
src/axi_xbar.sv

- `axi_xbar_intf`: Add interface variant of crossbar.
- `axi_atop_filter`: Fix ModelSim warnings by adding `default` statement.  The signal in the `case`   has a single bit, and both values were correctly handled in synthesis.  However, when starting   simulation, the signal has an undefined value, and ModelSim threw warnings that this violated the   `unique` condition.
- `axi_demux`: Move `typedef` outside `generate` for compatibility with VCS.
- `axi_id_prepend`:
- Fix text of some assertion messages.
- Fix case of prepending a single-bit ID.

Small improvements to atop_filter, demux, id_prepend, and xbar

---

Bender.yml
CHANGELOG.md
README.md
doc/README.md
doc/axi_lite_mailbox.md
scripts/run_vsim.sh
src/axi_lite_mailbox.sv
test/synth_bench.sv
test/tb_axi_lite_mailbox.sv
test/tb_axi_lite_mailbox.wave.do

Added an AXI LITE Mailbox.
Has two AXI LITE slave ports. The write of on port is connected to the other port via a FIFO and vice versa.
Each port has its own `irq_o` which can be configured to trigger on different conditions.
The irq's are `write threshold`, `read threshold` and `mailbox error`.
The added documentation in /doc/axi_lite_mailbox.md goes in detail over the usage of the module registers.
(Note: this pull request depends on the axi_test/rand_axi_lite_master from the axi_lite_xbar branch)

AXI4-Lite Mailbox implementation

---

CHANGELOG.md
src/axi_lite_to_apb.sv
test/synth_bench.sv
test/tb_axi_lite_to_apb.sv

* Change that the port `apb_req_o` is now an array with `NoApbSlaves` number of fields.
* The module now asserts that the width of the `psel` signal in the APB4 request struct is `1'b1`.
* The `apb_req_o` port is now default `'0` and only goes active for a correctly decoded slave on the respective port array field when an APB transaction takes place.

AXI4-Lite to APB4 Bridge: Change APB request port

---

CHANGELOG.md
src/axi_demux.sv

The `case` statement controlling the counters had not been specified `unique` even though it qualified for it.  This has been fixed.

axi_demux: Add `unique` to `case` distinction

---

CHANGELOG.md
src/axi_lite_mux.sv

This is a break-out of #43 with fixes to `axi_lite_mux_intf` that are independent of #43.

Fix axi_lite_mux_intf

---

CHANGELOG.md
src/axi_atop_filter.sv

When the connected slave module wants both AW and W to be valid before asserting thier readys, `axi_atop_filter` was stalling forever and did not let the W valid through.
Added a second condition for when AW is valid and non ATOP then the W handshake gets connected.

axi_atop_filter: Fix W handshake

---

CHANGELOG.md
src/axi_lite_to_apb.sv

- Change the interface version of the `axi_lite_to_apb` version to match the changes done in #59

AXI4-Lite to APB4 Bridge: Update interface version to match changed req ports 

---

CHANGELOG.md
src/axi_demux.sv

In case the `MaxTrans` parameter was set to 1, the `IdCounterWidth` was calculated to be 0.

axi_demux: Fix case when `MaxTrans` is 1

---

CHANGELOG.md
src/axi_atop_filter.sv
src/axi_intf.sv
src/axi_test.sv
test/tb_axi_atop_filter.sv

This fixes a couple of issues with the ATOP filter:
- A [recent change](https://github.com/pulp-platform/axi/commit/c4f97d9ac9c923ef7606da7033a7b0c557b2b2fa) broke the internal controller, which needs to relate W bursts to AW beats, not to W beats. Reverting this, however, led to underflows in an internal counter, due to [another recent change](https://github.com/pulp-platform/axi/pull/64). Counter underflows are now prevented through [additional conditions](https://github.com/pulp-platform/axi/commit/6bb4d4bf723549d38537e9b900a106fface860c2).
- The filter injected B and R responses even when the handshake of a beat signaled valid had not been completed yet.
The TB of the ATOP filter has been updated to cope with B bursts being fed through before AW beats.
Additionally, this PR improves …

Fix axi_atop_filter and improve verification master/slave

---

CHANGELOG.md
src/axi_cdc.sv
src/axi_cut.sv
src/axi_intf.sv
test/tb_axi_cdc.sv

This PR removes the global package imports of `axi_pkg` in synthesizable modules. I ran into issues with Verilator, where the global namespace was broken due to the package defining `resp_t` and subsequest modules defining a parameter `resp_t` in thier definition.
I further did some port naming cleanup and removed interfaces which are no longer used by the modules in this repo.
Changes:
- `axi_cdc`: Add AXI4-Lite interface wrap.
- `axi_intf`: Add AXI4-Lite `prot_t` signal, adapted macros accordingly.
- `axi_cdc`: Change ports `src` and `dst` to `slv` and `mst`.
- `axi_cut`: Change ports `in` and `out` to `slv` and `mst`.
- `axi_multicut`: Change ports `in` and `out` to `slv` and `mst`.
- `axi_intf`: Removed global `import axi_pkg::*;`, made package calls explicit.
- `tb_axi_cdc`: Removed …

Remove global package imports

---

CHANGELOG.md
src/axi_lite_to_axi.sv
src/axi_lite_xbar.sv
test/synth_bench.sv
test/tb_axi_lite_to_axi.sv

Reportedly, Xcelium (version unknown) cannot handle hierarchical expressions (e.g., `mst_req_o.w.data`) as argument to the `$bits()` function. I propose to fix this in this PR by adding a parameter for the data width.  The disadvantage is that this is a backwards-incompatible "API" change. I am open to backwards-compatible suggestions, of course.
As we currently do not have regression tests for Xcelium, -- at the moment we cannot verify every version of every tool with its own flavor of SystemVerilog -- I suggest to fix similar issues reactively on a per-case basis.

axi_lite_to_axi: Add Data Width parameter to fix synthesis in Xcelium

---

CHANGELOG.md
src/axi_dw_downsizer.sv
src/axi_dw_upsizer.sv
test/tb_axi_dw_downsizer.sv
test/tb_axi_dw_upsizer.sv

The indices of the data lanes seem swapped (tracing values shows out-of-bound indices). Maybe this happened during the last-minute rename of master/slave width terminology.
@suehtamacv Can you please confirm this fix? Do other code parts come to your mind that could have the same problem?

dw_converter: Fix lane steering and serialization

---

CHANGELOG.md
src/axi_test.sv

`axi_test`: `rand_axi_master`: Fix for stuck on read receive in ATOP mode
Scenario was:
* Have `rand_axi_master` in `ATOP` mode.
* Issue `.run()`
* Reads complete, but writes are still continuing, read is ready as a new ATOP with read response could follow
* No ATOP with read response follows -> master waits for read response forever

rand_axi_master: Fix stuck on read receive in ATOP mode

---

CHANGELOG.md
src/axi_lite_to_axi.sv
test/synth_bench.sv
test/tb_axi_lite_to_axi.sv

There is no clear suggestion in the AXI standard on what to do with the cache signals when converting from AXI-Lite to full AXI. This PR exposes the `AxCACHE` signals so that the user can decide on what to do.

axi_lite_to_axi: Expose `AxCACHE` signals

---

.ci/Memora.yml
.gitlab-ci.yml
Bender.yml
CHANGELOG.md
src/axi_dw_upsizer.sv
src/axi_pkg.sv
src/axi_test.sv
test/tb_axi_addr_test.sv

This adds support for all burst types in `axi_pkg::beat_addr`.
Function now has two more inputs as they are required to calculate the wrap boundary in a wrapping type burst:
* `axi_pkg::len_t len`
* `axi_pkg::burst_t burst`
All occurrences in this repo have been updated to the new inputs.

axi_pkg::beat_addr: Add support for all burst types

---

CHANGELOG.md
include/axi/assign.svh
src/axi_intf.sv
src/axi_test.sv

This introduces the class `axi_scoreboard` in `src/axi_test`.
* Add `Monitor` modport in `AXI_BUS_DV`.
* Add `AXI_ASSIGN_MONITOR` macro to assign a `AXI_BUS` interface to a monitor interface.
* Models the accessed memory space of the monitored AXI4+ATOP channel.
Assumes the memory can only be changed from the AXI channel.
* Handles ambiguous data when reads are performed on memory locations currently written to.

AXI Scoreboard

---

.ci/Memora.yml
.gitlab-ci.yml
Bender.yml
CHANGELOG.md
README.md
src/axi_serializer.sv
src_files.yml
test/synth_bench.sv
test/tb_axi_serializer.sv
test/tb_axi_serializer.wave.do

* Adds `axi_serializer` from #91.
* Adds ATOP support to the module `axi_serializer`.
* Functional and Synthesis testbench for `axi_serializer`.

AXI Serializer

---

CHANGELOG.md
src/axi_burst_splitter.sv
src/axi_dw_downsizer.sv
src/axi_dw_upsizer.sv
src/axi_pkg.sv

This adds a function to `axi_pkg`, that returns whether the AXI transactions are modifiable/bufferable based on the value of their `axcache`. This replaces a common pattern such as
```sv
// The AXI Spec (A3.4.1) only allows splitting non-modifiable transactions ..
if (!(|(cache & axi_pkg::CACHE_MODIFIABLE)))
```
by
```sv
// The AXI Spec (A3.4.1) only allows splitting non-modifiable transactions ..
if (!axi_pkg::modifiable(cache))  
```

axi_pkg: Add modifiable and bufferable helper functions

---

CHANGELOG.md
src/axi_dw_converter.sv
src/axi_dw_downsizer.sv
src/axi_dw_upsizer.sv

This PR adds support for `FIXED` transactions in the DWCs. 
It is trivial to upsize `FIXED` transactions, and the upsized AXI transaction is identical to the original. 
Downsizing them, however, is more complex:
-  If the incoming `FIXED` transactions have an `axsize` not wider than the outcoming port, the DWC can forward the transaction without any changes.
- Otherwise, each data beat of the incoming `FIXED`  transaction must be transformed into an `INCR` burst.
The downsizer currently does not support `FIXED` bursts. It would be possible to support them by converting them into a sequence of `INCR` bursts. But I wonder whether this is a common enough use case to require the support of the downsizer. If such bursts are needed, an alternative would be to use an `axi_burst_splitter` in …

Add support for FIXED transactions in the DWCs

---

CHANGELOG.md
src/axi_test.sv

rand_axi_master: Respect burst type restrictions in ATOPs

---

src/axi_lite_demux.sv

Hello!
In this pull request I added missing type parameters in initialization axi_lite_demux.

added req_t and resp_t on initialization axi_lite_demux

---

src/axi_dw_downsizer.sv
src/axi_dw_upsizer.sv
src/axi_test.sv

This PR breaks the critical path of the DWCs. This is done through an extra state at the read up/downsizer FSMs, by making injected AW requests take one extra cycle. AW injection in the read up/downsizers happens in one cycle, and the evaluation of the read up/downsizing parameters happens at the next cycle.
This PR solves #123, and depends on #102.

Improve timing of the DWCs

---

Bender.yml
CHANGELOG.md
scripts/run_vsim.sh
src/axi_dw_downsizer.sv
src/axi_dw_upsizer.sv
src/axi_pkg.sv
src/axi_test.sv
test/tb_axi_dw_downsizer.do
test/tb_axi_dw_downsizer.sv
test/tb_axi_dw_pkg.sv
test/tb_axi_dw_upsizer.do
test/tb_axi_dw_upsizer.sv

This adds two monitors in the `tb_axi_dw_pkg.sv` file, against which the DW converters are compared on the TB.

Add golden models for the DW Converters

---

Bender.yml
CHANGELOG.md
ips_list.yml
src_files.yml

* Bump `common_cells` to  fixed version of `v1.20.0` (see https://github.com/pulp-platform/common_cells/pull/104)
* Link against `common_cells_lib`
* Fix include path. Note ipapprox has no understanding of include paths of dependencies or an option for global include paths (afaik). Anyway we have the same hack in other IPs such as fpnew and I'd rather benderize than hack around ipapprox more.

Fix ipapprox deps

---

CHANGELOG.md
src/axi_xbar.sv

This is a workaround for a problem with vsim 10.6c, see issue #133.
That version of vsim reports an "illegal output or inout port connection
for port 'slv_resp_o'" error (`vsim-3053`).  More recent versions of
vsim do not have this problem.
This workaround preserves the original functionality.
Thanks @jsailer for implementing this in https://github.com/jsailer/axi/commit/877364c130ed14dce4016410ea004008a118e7ca.
Fixes #133.

axi_xbar: Improve compatibility with vsim 10.6c

---

CHANGELOG.md
scripts/run_vsim.sh
test/tb_axi_lite_regs.sv

This fixes #122.
The tb performs a known write followed by a read at the begining of simulation to a writeable address. The hardcoded data read assertion can be safely removed as the read data is checked by `proc_check_read_data` at the same time against the dynamic model.
Also added some more parameters in the vsim run script for the tb.

Fix issue 122

---

.ci/Memora.yml
.gitlab-ci.yml
scripts/run_vsim.sh

CI now includes Questa 2020.1. This PR therefore closes #78, as all tests pass also with Questa 2020.1.

CI: Test multiple recent vsim versions

---

.github/workflows/doc.yml

PRs from forks currently fail because they cannot *deploy* the documentation.  This disables the deployment of documentation from forks.

workflows/doc: Only deploy from base repo

---

src/axi_id_remap.sv

Very minor fix. Since the `w` channel has no `id` and is directly forwarded from the input to the output, we can check that the width of the whole channel matches at the input and output. Thereby, the `data`, `strb`, and `user` signals have to match.
Would you prefer checking the `w.data` and the `w.user` width separately to eliminate the case where both signals' width mismatch, but the total width is the same for both ports?

axi_id_remap: Check the width of the whole `w` channel

---

CHANGELOG.md
src/axi_test.sv

For the random AXI master it can be interesting to also randomize the
qos signal, especially in view of achieving any code coverage on logic
dependent on this signal.

axi_test: Randomize `qos`

---

CHANGELOG.md
src/axi_test.sv

This patch makes it optional for a random slave to randomize the success
of any accesses. The default is off, so any existing code should be
still compatible.
Again, useful for achieving code coverage on error conditions of any
modules.

axi_test: Optionally randomize responses

---

Bender.yml
CHANGELOG.md
ips_list.yml
test/tb_axi_addr_test.sv
test/tb_axi_atop_filter.sv
test/tb_axi_cdc.sv
test/tb_axi_dw_downsizer.sv
test/tb_axi_dw_upsizer.sv
test/tb_axi_isolate.sv
test/tb_axi_lite_mailbox.sv
test/tb_axi_lite_regs.sv
test/tb_axi_lite_to_apb.sv
test/tb_axi_lite_xbar.sv
test/tb_axi_modify_address.sv
test/tb_axi_serializer.sv
test/tb_axi_sim_mem.sv
test/tb_axi_xbar.sv

This PR updates the `common_verification` dependency.
This includes renaming parameters of called modules for compatibility, removing `timeunit/timeprecision` arguments, and updating the `common_cells` dependency with the same updates, avoiding version conflicts.

Update `common_verification` dependency

---

Bender.yml
scripts/run_verilator.sh
scripts/synth.sh
test/axi_synth_bench.sv
test/synth_bench.sv

There was a need to rename the `synth_bench` to `axi_synth_bench` as it would collide with `common_cells` `synth_bench`. I will do the same for the `common_cells` but I figured it would be good to fix this in any case (thanks for the good namespacing support SV :-)).
Furthermore, there it contains a small fix with the unpacked array literals.
Verilator 4.100 works fine with the synthesis testbench but we got quite some warnings. I think we should go through them and figure out which one we want to waive. Then we can also check, that new additions to the repo don't cause any new warnings.
The next step will be to add Verilator to the CI regression, first to check for incompatible constructs, second to check the lint warnings.

Add Verilator script

---

CHANGELOG.md
include/axi/assign.svh

`assign.svh`: Add macros for assigning between AXI-Lite `struct`s, both inside a process (`AXI_LITE_SET_*_STRUCT`) and outside a process (`AXI_LITE_ASSIGN_*_STRUCT`).  This is safer than assigning `struct`s with a simple `=`, because the macros assign individual fields.

assign.svh: Add macros for assigning between AXI-Lite structs

---

.ci/Memora.yml
Bender.yml
CHANGELOG.md
axi.core
src/axi_cdc.sv
src/axi_cdc_dst.sv
src/axi_cdc_src.sv
src/axi_intf.sv
src_files.yml

1. The implementation of `axi_cdc` is replaced with an instance of `axi_cdc_src` connected to an instance of `axi_cdc_dst`.
2. `axi_cdc_*` use `parameter type aw_chan_t = logic` (and similar for the other channels), as is currently done for `axi_cdc`.  
3. The main implementation of `axi_cdc_src` and `axi_cdc_dst` use `struct`s as ports and format parameter names as `lower_snake_case`    for types and `UpperCamelCase` for numbers.  
4. Added also the async interfaces definition

axi_cdc: Modularize into source and destination side

---

CHANGELOG.md
src/axi_demux.sv

Improve compatibility with new version of QuestaSim's optimizer (`vopt`).  Before this workaround, QuestaSim 2020.2 and 2021.1 could segfault on instances of `axi_demux`.

axi_demux: Introduce workaround for bug in new vopt

---

src/axi_test.sv

This refactors the ID legalization of the randomizing AXI master (a testbench class) into one function, `legalize_id()`, which legalizes the ID of the given beat according to the current in-flight transactions.  To determine if an ID is currently legal, that function calls another new function, `id_is_legal()`.  With this, the conditions under which an ID is legal became much easier to understand: they are now concentrated in a single function with only 10 LOC and without deeply nested conditionals.
This prepares the randomizing AXI master for an upcoming feature extension, which allows to constrain it to issue transactions with IDs that are unique among all in-flight transactions.

axi_rand_master: Refactor ID legalization

---

CHANGELOG.md
src/axi_lite_to_apb.sv

Version 0.28.0 introduced new parameters for the `axi_lite_to_apb` module (`PipelineRequest` and `PipelineResponse`). However, the new parameters are missing in the SV Interface wrappers. This PR fixes this issue.

Add new parameters in axi_lite_to_apb to interface wrapper

---

CHANGELOG.md
src/axi_cdc_src.sv

It seems the `_i/_o` suffixes got interchanged when instantiating the `axi_cdc_src` module. I do not use this module directly, but Verilator gave me a warning when compiling the `axi` repo.

axi_lite_cdc_src_intf: Fix interchanged ports

---

CHANGELOG.md
src/axi_dw_downsizer.sv
src/axi_dw_upsizer.sv

Closes #184.
This PR reworks a construct that would case latches to be infered on both the `axi_dw_downsizer` and the `axi_dw_upsizer`, when synthesizing them with the Mentor Precision.

Fix latch inference on the data width converters with the Mentor Precision synthesis tool

---

CHANGELOG.md
src/axi_demux.sv

Closes #187.
This PR guards the workaround of #169 between `TARGET_VSIM` guards, because that workaround was not understood by VCS 2020.12.

axi_demux: Improve compatibility with VCS

---

CHANGELOG.md
src/axi_demux.sv

As discussed in https://github.com/pulp-platform/axi/issues/202 I submit a PR for the prefered solution (also consistent with `axi_lite_demux`)

Generalize questa 2020/21 work-around

---

CHANGELOG.md
src/axi_id_remap.sv

Verilator doesn't like asserts.

axi_id_remap: Fix verilator ifndef not covering asserts

---

CHANGELOG.md
src/axi_cdc_dst.sv
src/axi_cdc_src.sv

Improve compatibility of `axi_cdc` with VCS by restricting a QuestaSim workaround to be used only for QuestaSim. This fixes issue #207.

axi_cdc: Improve compatibility with VCS

---

CHANGELOG.md
src/axi_xbar.sv

VCS seems to be unable to handle constant function calls whose argument is a `struct` passed into a module as `parameter`.  `axi_xbar` became prone to this problem with commit d24303f0df9.  This commit works around the problem by calling a system function instead of a constant function.

axi_xbar: Work around constant function calls for VCS

---

CHANGELOG.md
src/axi_sim_mem.sv

Add a monitoring interface into the `axi_sim_mem` to observe the Point of Coherency between the write and the read channel.
#216 Has to be merged first.

axi_sim_mem: Add monitoring interface

---

CHANGELOG.md
src/axi_sim_mem.sv

The AR channel's user signal was not correctly propagated to the monitor interface since we do not reflect the user signal. As the R and AR channels do not have the same user signals, it makes sense to use the AR's signal for the monitoring interface since this is the one the user has control over and might want to observe.

axi_sim_mem: Propagate the ar_user signal correctly to the monitor

---

CHANGELOG.md
src/axi_demux.sv
src/axi_lite_demux.sv
src/axi_lite_mux.sv
src/axi_mux.sv

axi_{,lite_}{,de}mux: Add missing spill registers for single master/slave port configurations

---

CHANGELOG.md
src/axi_demux.sv

Eliminate unnecessary stalls of AW channel when the AR channel has
reached its maximum number of transactions.  Prior to this fix,
`axi_demux` would always stall AWs while read transactions were at their
maximum (that is, while `MaxTrans` read transactions were outstanding).
However, this stall is only required when the AW that is being handled
by `axi_demux` is an atomic operation (ATOP) that entails an R response.
This fix therefore removes unnecessary stalls as well as an unnecessary
dependency between reads and writes.  The integrity of data or
transactions was not affected by this problem.

axi_demux: Eliminate unnecessary AW channel stalls

---

CHANGELOG.md
src/axi_intf.sv

This PR is related to issue #240. It adds a Monitor modport on the AXI_BUS and AXI_LITE interfaces.

Add Monitor modport to AXI_BUS and AXI_LITE interfaces

---

Bender.yml
CHANGELOG.md
README.md
axi.core
src/axi_to_mem.sv
src_files.yml

This PR adds the `axi_to_mem` module to translate AXI4 to a simple memory protocol. This PR partially replaces #115 and #213.

AXI4 on chip memory slave

---

CHANGELOG.md
src/axi_lite_demux.sv
src/axi_test.sv

Included are the following changes:
- axi_test:
- axi_test: Use `beat_addr` function
- axi_test: Add mapped mode to random classes
- axi_test: Additions to scoreboard class
- axi_lite_demux: 
- axi_lite_demux: Increase VSIM compatibility
- axi_demux (***amended***): 
- axi_demux: Replace w_fifo with a write counter

First batch of fixes and improvements originating from the `axi_llc` branch

---

.ci/Memora.yml
.gitlab-ci.yml
Bender.yml
CHANGELOG.md
README.md
axi.core
scripts/compile_vsim.sh
scripts/run_vsim.sh
src/axi_to_mem_banked.sv
src_files.yml
test/axi_synth_bench.sv
test/tb_axi_to_mem_banked.sv

This PR adds a banked variant of `axi_to_mem` for higher throughput. This PR also adds a test for `axi_to_mem_banked`, which also tests `axi_to_mem` as it is called within the new module. This PR partially replaces #115 and #213 and depends on #244.

AXI4 banked on chip memory slave

---

.ci/Memora.yml
.gitlab-ci.yml
Bender.yml
README.md
axi.core
scripts/run_vsim.sh
src/axi_fifo.sv
src_files.yml
test/tb_axi_fifo.sv
test/tb_axi_fifo.wave.do

This adds the `axi_fifo` module that puts a `fifo_v3` in all five AXI4 channels to buffer requests and responses.
Solves #191.

Add module `axi_fifo`

---

src/axi_test.sv

Having a parameter to only have aligned accesses could be useful in certain stages of development.
If you agree it is a feature worth mentioning, we could then also discuss the proper way to implement it.

`axi_tb`: add option for aligned accesses of given `ax_size`

---

src/axi_dw_downsizer.sv

This modification allows to correctly forward the response status of multi-beat exclusive write operations.
This RESP_EXOKAY response code has the lowest priority (as defined by the axi_pkg::resp_precedence function) when merging the response code from a multi-beat write response. Without this modification, a successful exclusive access can never get the corresponding RESP_EXOKAY code.

axi_dw_downsizer: initialize the write response buffer with EXOKAY

---

CHANGELOG.md
src/axi_chan_compare.sv

In some cases the ID is modified/remapped on purpose, which triggers the compare module. This PR adds a parameter `IgnoreId` which ignores the ID field while still checking all the other fields.

axi_chan_compare: Support remapped IDs

---

src/axi_pkg.sv

\[ From issue https://github.com/pulp-platform/axi/issues/292 \]
Since commit [fe4e020](https://github.com/pulp-platform/axi/commit/fe4e020f2c06a242d4901b23cedbf2eeab22bfe6) the typedef`axi_pkg::burst_t` now relies on a Verilog parameter `BurstWidth`.
https://github.com/pulp-platform/axi/blob/fd60be8b51a4fa7476856be162ce3334474592ba/src/axi_pkg.sv#L46
In [Occamy emulation](https://github.com/pulp-platform/snitch/blob/master/hw/system/occamy/src/occamy_xilinx.sv) we use these typedefs at the ports of a custom packaged Vivado IP.
But Vivado requires that "the IP ports are contained within the port description of the HDL file" (c.f. [doc](https://www.xilinx.com/support/documents/sw_manuals/xilinx2022_1/ug1118-vivado-creating-packaging-custom-ip.pdf) page 14).
So custom Vivado IPs can't use …

axi_pkg: keep hardcoded value in typedef for vivado ip packager

---

src/axi_id_serialize.sv

This extends `axi_id_serialize` with three new parameters in a backward-compatible fashion:
* `MstIdBaseOffset`:  a custom offset (modulo `AxiMstPortMaxUniqIds`) for the assigned output IDs.
* `IdMap`: an optional explicit input-output ID map. If an input ID `id` does not appear in this map, it is mapped to the output ID `(id + MstIdBaseOffset) % AxiMstPortMaxUniqIds` as in the existing design. If `id` appears in more than one entry, it is matched to the *last* matching entry's output ID.
* `IdMapNumEntries`: Number of Entries in `IdMap` (default: 0).

axi_id_serialize: Add optional ID base and map parameters

---

src/axi_cdc.sv
src/axi_cdc_dst.sv
src/axi_cdc_src.sv

Here is a minor update to the CDCs.
The only changes are related to the propagation of the sync_stages parameter to the internal cdc_gray.
It is useful to set a different number of synchronization registers.

Propagation of the cdc gray SYNC_STAGES parameter to the interfaces

---

src/axi_to_mem_interleaved.sv

Adds a module with an SystemVerilog interface analogous to the one in `axi_to_mem_banked`.

axi_to_mem_interleaved: Add interface version

---

src/axi_burst_splitter.sv
src/axi_to_axi_lite.sv

This PR exposes the `FULL_BW` parameter of the `id_queue` module in the `axi_burst_splitter` and `axi_to_axi_lite` IPs. This enables AXI testbench memories built with these components to have full bandwidth, i.e. respond with a maximum throughput of one R beat every cycle.

axi_burst_splitter: Expose id_queue module's FULL_BW parameter

---

src/axi_test.sv

If the access is misaligned the subordinate does not need to fill the don't care bytes with the the stored values.

`axi_scoreboard`: avoid false negs for mem-mapped misaligned reads.

---

.ci/Memora.yml
.github/workflows/doc.yml
.github/workflows/gitlab-ci.yml
Bender.yml
CHANGELOG.md
src/axi_to_detailed_mem.sv

Fixes #319
Requires https://github.com/pulp-platform/common_cells/pull/194 to be released

Properly handle response code in axi_to_detailed_mem

---

src/axi_to_mem_interleaved.sv
src/axi_to_mem_split.sv

Corrects some missing pin warnings raised by Verilator 4.110.

src: Remove missing pin warnings

---

src/axi_sim_mem.sv

Hi all!
I found this bug when accessing the simulation RAM with `ax.size = 0` and 32-bit data bus.
During an increment access to the memory, when `r_cnt % strb_width != 0`, the address of the location accessed (`addr`) is calculated with `ax_queue[0].addr` (e.g. 2nd beat of an INCR burst at location 0x10 has an address of 0x11), but then `addr` is used to determine the byte in the 32-bit word, causing it to make the offset with 0x11 instead of 0x10.
In particular, for `r_cnt = 1`, the byte calculated was 2 instead of 1.

Fix byte calculation in axi_sim_mem R and W forks

---

CHANGELOG.md
src/axi_sim_mem.sv

Allow response data for uninitialized region to have configurable defined value, based on a parameter.

`axi_sim_mem`: Configure response data

---

CHANGELOG.md
src/axi_bus_compare.sv
src/axi_slave_compare.sv

- Fix mismatch detection
- Consider size field for comparison

Fix bus compare

---

CHANGELOG.md
scripts/run_vsim.sh
src/axi_dw_downsizer.sv
test/tb_axi_dw_downsizer.sv

The `forward_b_beat_push` signal should be asserted every time the last `W` handshake in a burst occurs on the master port. However, pushing to the FIFO should also be conditional on `forward_b_beat_full` not being asserted.
The way this second condition was ensured allowed the `W` handshake to occur, without tracking it through a push to the queue. The corresponding `B` handshake would then trigger a pop, causing an underflow in the FIFO counter.
This PR corrects this behaviour, by stalling the `W` handshake until the FIFO is no longer full, so it is ensured that pushing to the FIFO is possible.

axi_dw_downsizer: Fix `i_forward_b_beats_queue` underflow

---

CHANGELOG.md
src/axi_intf.sv
src/axi_test.sv
test/tb_axi_sim_mem.sv

AXI_BUS_DV: Assert burst on one page

---

CHANGELOG.md
src/axi_id_serialize.sv

Rewrite simpler axi_id_serializer

---

.ci/Memora.yml
CHANGELOG.md
src/axi_xbar_unmuxed.sv

multi-dimensional array interfaces are not yet supported in VCS

axi_xbar_unmuxed: Disable for VCS compilation

---

src/axi_id_serialize.sv

Revert #342, which prevented CVA6 Linux boot in Cheshire.

 Revert #342 (b9915f5) to temporarily fix axi_id_serialize 

---

src/axi_id_serialize.sv
src/axi_pkg.sv

`axi_id_serialize_intf` such as used [here](https://github.com/pulp-platform/cheshire/blob/main/target/sim/src/vip_cheshire_soc.sv#L686) calls `axi_id_serialize` without setting IdMapNumEntries. This causes VCS to complain about an array bound greater than 2^31-1.
Thus, iomsb function may be useful in axi.

axi_pkg: Add iomsb to avoid underflow in array lengths

---

src/axi_rw_split.sv

Hello,
I believe there is a simple typo in the assertions of axi_rw_split. Currently, it is checking that the read channel's read valid signal should not go high. I believe that it should be checking the write channel instead.
Best regards

axi_rw_split: Fix write channel assertions

---

src/axi_sim_mem.sv
src/axi_test.sv
test/tb_axi_dw_pkg.sv
test/tb_axi_xbar_pkg.sv

Minimal changes required to compile sources and simulation targets for VCS (version W-2024.09-1) and Verilator (v5.028-44-g1d79f5c59):
- Verilator requires the `std::` prefix when using built-in classes like `std::semaphore` and `std::mailbox`.
- Verilator cannot compute static variables at compile time when conditional operator is used.
- Verilator cannot determine the default type for Associative Arrays if a parameter is used.
- VCS requires parameter types to match when calling a function with a class object. If any of the axi_??_beat classes are instantiated directly and not from the typedefs in axi_driver, they cannot be passed to a function of a axi_driver object, as `parameter` and `parameter int` are not the same.

VCS and Verilator support

---

src/axi_dw_upsizer.sv

As detailed in #361, Verilator versions v5.028+ have issues with a statement in `axi_dw_upsizer.sv`. Contrary to my initial assumption, it seems that the root cause of the problem is actually the width of the data type of `mst_port_offset` and `slv_port_offset` and not its sign. Hence, this PR reduces the width of these signals to the width that is actually used and assigned on lines 485 and 486.
While this is actually a bug in Verilator, I would be very grateful if the maintainers of this repository are willing to accept this workaround.

src/axi_dw_upsizer.sv: avoid unnecessarily wide indices into r_data

---

test/tb_axi_dw_pkg.sv

This PR refactors the AXI module constructors in `test/tb_axi_dw_pkg.sv` by removing redundant `begin...end` blocks. The primary objective is to streamline the constructor definitions to account for parser errors occurring in the `sv-parser` crate used by [morty](https://github.com/pulp-platform/morty). 
- The removal addresses parsing issues related to `super.new(...)` calls, ensuring that the `sv-parser` can accurately interpret method calls without being constrained by unnecessary block delimiters.
- The `begin...end` blocks within constructors were redundant, as the constructor's logic doesn't require multiple procedural statements that necessitate such blocks.
The functional behavior and RTL characteristics of the AXI module remain **unchanged**. The constructor continues to …

[test] Remove begin/end from constructors to fix morty ci err

---

src/axi_lite_lfsr.sv

Explicitly declare `w_b_fifo_valid` to avoid inferred nets.

axi_lite_lfsr: Add missing signal declaration

---

src/axi_to_mem_interleaved.sv

Minor fix,  previously `busy_o` was not driven (discovered via Vivado warnings)

axi_to_mem_interleaved: fix busy signal

---

src/axi_dw_downsizer.sv

Same problem as in https://github.com/pulp-platform/axi/pull/362, but for the AXI downsizer this time. Verilator has issues indexing with wide (e.g. 48-bit addresses).

axi_dw_downsizer: Fix unnecessarily wide indices for verilator compatibility

---

CHANGELOG.md
src/axi_cut.sv

Add the parameters  BypassAw, BypassW, BypassB, BypassAr, BypassR which are by default all assigned to the already existing parameter Bypass. This allowes selectively bypassing the cut on certain channels. This is useful to only cut the channels that lead to timing issues.

Axi_cut: Add selective channel bypassing

---

src/axi_burst_splitter.sv
src/axi_lite_to_apb.sv

- Drop APB write requests with '0 write strobe
- Fix burst splitter addr alignment
- Align APB addr to avoid possibly unpredictable behavior

APB converter fixes

---

src/axi_to_detailed_mem.sv

The dead response FIFO could previously underflow, because the surrounding code could present a valid read response (`rvalid_o`) based on `dead_response`, without considering whether `dead_response` was actually valid.

axi_to_detailed_mem: Avoid spurious write responses with HideStrb

---

src/axi_burst_unwrap.sv

This PR fixes a bug in the `axi_burst_unwrap` module, where the `id_queue` managing a write burst's outstanding W beats receives decrement requests even if the W channel transfer was not handshaked.

axi_burst_unwrap: Remove overly pessimistic assertion

---

Bender.yml
README.md
axi.core
src/axi_inval_filter.sv
src_files.yml

Listens to the AW channel and issues cacheline invalidation requests. Source and file history are imported from [Ara](https://github.com/pulp-platform/ara/blob/a6436df6ad4011c77b5b40e0432acdbf4668639f/hardware/src/axi_inval_filter.sv),

Add AXI invalidation filter
