- scripts/run_vsim.sh
- test/tb_axi_lite_xbar.sv
Fixes the problem reported in #21.
> tb_axi_lite_xbar: Fix AW->W dependency and increase handshake randomness

- CHANGELOG.md
- src/axi_to_axi_lite.sv
It seems that I've fixed underflow conditions here. I guess that was in conjuction with eh billywig tape-out.
> Fix axi to axi lite

- src/axi_test.sv
- src_files.yml
* iapprox: Do not add unneeded files
* tb: Fix scope of package include
* tb: Add default params
> Various fixes

- CHANGELOG.md
- test/tb_axi_xbar.sv
fix for issue [#51](https://github.com/pulp-platform/axi/issues/51)
> tb_axi_xbar: fix issue 51

- CHANGELOG.md
- src/axi_intf.sv
> axi_intf: Improve Verilator compatibility

- src/axi_pkg.sv
@fabianschuiki and I are working on an automatic documentation generation using [morty](https://github.com/zarubaf/morty). We thought that the AXI package would make for an interesting proof of concept with the added benefit that we would further improve the documentation. 😄 
For a preview of what is currently possible to generate: https://iis-people.ee.ethz.ch/~zarubaf/doc/package.axi_pkg.html which has been automatically generated from the changes in this PR.
> axi_pkg: Add doc comments

- Bender.yml
- CHANGELOG.md
- README.md
- scripts/run_vsim.sh
- src/axi_isolate.sv
- src/axi_pkg.sv
- src_files.yml
- test/synth_bench.sv
- test/tb_axi_isolate.sv
- test/tb_axi_isolate.wave.do
> AXI Isolate

- include/axi/assign.svh
Fixes nuisance warning messages with Cadence Genus HDL parser
> Fix extra semicolon at end of line

- CHANGELOG.md
- src/axi_lite_to_apb.sv
> axi_lite_to_apb: Fix strobe width assertion message

- .ci/Memora.yml
- .gitlab-ci.yml
- Bender.yml
- CHANGELOG.md
- src/axi_modify_address.sv
- test/synth_bench.sv
- test/tb_axi_modify_address.sv
This fixes a variety of problems and shortcomings of `axi_modify_address` and its interface variant; details are in the Changelog.
> axi_modify_address: Various fixes and improvements

- src/axi_dw_downsizer.sv
- src/axi_pkg.sv
This solves issue #108 and depends on PR #102.
>  axi_dw_downsizer: Response after transaction splitting 

- src/axi_dw_downsizer.sv
Before this change, `slv_resp_o.aw_ready` could be asserted even though `forward_b_beat_full`.  When that happened, the AW and W beat were not forwarded but dropped in the DWC, and upstream never got a B response for that transaction back.
To fix this, new writes in the *idle* state are only handled if `!forward_b_beat_full`.  For this, the logic handling the *idle* state has been wrapped in a [new `if` statement](https://github.com/pulp-platform/axi/pull/118/files#diff-3601b4c67184ff301f29a4fe12c0d371R699).  (The additional level of indentation confuses GitHub diff.)
> axi_dw_downsizer: Fix overflow of B forward FIFO

- .github/workflows/doc.yml
- README.md
> Fix auto-generated documentation and mention it in ReadMe

- CHANGELOG.md
- src/axi_test.sv
- test/tb_axi_delayer.sv
> Fix `randomize()` for class variables

- src/axi_lite_demux.sv
- src/axi_test.sv
- test/tb_axi_xbar.sv
These are a couple of backwards-compatible changes to improve compatibility with VCS.
> Improve compatibility with VCS (1/2)

- CHANGELOG.md
- src/axi_intf.sv
- src/axi_test.sv
> Improve compatibility with VCS (2/2)

- scripts/compile_vsim.sh
> Compile with linting and pedantic error checking

- Bender.yml
- CHANGELOG.md
> Update `common_cells` to 1.20.1 to fix #150

- README.md
- src/axi_test.sv
> Update references and links to the AMBA 5 specification

- CHANGELOG.md
- src/axi_lite_mux.sv
> axi_lite_mux_intf: Fix type of interface ports

- CHANGELOG.md
- src/axi_lite_mux.sv
Reduce complexity of W channel at master port by removing an unnecessary multiplexer.
Resolves #243.
> axi_lite_mux: Reduce complexity of master port W channel

- .ci/Memora.yml
- .gitlab-ci.yml
- Bender.yml
- CHANGELOG.md
- README.md
- axi.core
- scripts/compile_vsim.sh
- scripts/run_vsim.sh
- src/axi_to_mem_banked.sv
- src/axi_to_mem_interleaved.sv
- src/axi_to_mem_split.sv
- src_files.yml
- test/axi_synth_bench.sv
- test/tb_axi_to_mem_banked.sv
Interleaved and split variant of axi_to_mem
> axi_to_mem split & interleaved

- Bender.yml
- CHANGELOG.md
- scripts/axi_dumper_interpret.py
- src/axi_dumper.sv
This module dumps a log from an AXI bus, which can be analyzed with the interpret script for debugging purposes.
> Add `axi_dumper` and `axi_dumper_interpret` script.

- Bender.yml
- CHANGELOG.md
- README.md
- axi.core
- src/axi_bus_compare.sv
- src/axi_slave_compare.sv
- src_files.yml
- test/tb_axi_bus_compare.sv
- test/tb_axi_slave_compare.sv
They will be moved to the `test` directory in the next PR.
> Add synthesizable verification modules that compare two buses and two slave devices.

- .ci/Memora.yml
- .gitignore
- .gitlab-ci.yml
- Bender.yml
- CHANGELOG.md
- README.md
- scripts/run_vsim.sh
- src/axi_lite_dw_converter.sv
- src/axi_test.sv
- test/axi_synth_bench.sv
- test/tb_axi_lite_dw_converter.sv
Rebase of a 2-year old branch:
axi_lite_dw_downsizer: Add AXI4-Lite data width downsize conversion module
axi_test:rand_axi_lite_slave: R response field is now random
axi_lite_sw_converter: Add to synth bench
> Axi lite dw converter
